spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        format_sql: true
#        show_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace